AlwaysOnPlayerHPLine=false
Autopause=false
AutosaveWorldFrequency=720
BuildGrid=true
Debug=2
DetectLanguage=false
EffectsVolume=100
InterpolateSunset=true
Language=ru
PreloadResources=true
ShowPrompts=true
SoundsVolume=100
TargetFPS=75
VerticalSync=false
SmoothedCamera=true
DebugMACOSX=false
