AlwaysOnPlayerHPLine=false
Autopause=true
AutosaveWorldFrequency=7200
BuildGrid=true
Debug=0
DebugMACOSX=false
DetectLanguage=false
EffectsVolume=100
InterpolateSunset=true
Language=en
PreloadResources=true
ShowPrompts=true
SmoothedCamera=true
SoundsVolume=100
TargetFPS=0
VerticalSync=true
EnableExpFeatures=false
